# Generated by Django 4.1.6 on 2023-02-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(db_column="CLIENT_CODE", max_length=20)),
                ("price", models.IntegerField(db_column="PRICE", null=True)),
                ("taxes", models.IntegerField(db_column="TAXES", null=True)),
            ],
            options={
                "verbose_name": "SALE",
                "db_table": "SALE",
            },
        ),
    ]
