# Generated by Django 4.1.6 on 2023-02-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="created_date",
            field=models.DateTimeField(
                db_column="FECHA_CREA", editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="updated_date",
            field=models.DateTimeField(
                db_column="FECHA_MODIFICA", editable=False, null=True
            ),
        ),
    ]
