# Generated by Django 4.1.6 on 2023-02-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "code",
                    models.CharField(
                        db_column="ID", max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="NAME", max_length=20)),
                ("state", models.CharField(db_column="STATE", max_length=1)),
                (
                    "created_date",
                    models.DateTimeField(db_column="FECHA_CREA", editable=False),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        db_column="FECHA_MODIFICA", editable=False, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "USERS",
                "db_table": "USER",
            },
        ),
    ]
