# Generated by Django 4.1.6 on 2023-02-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="price",
            field=models.IntegerField(db_column="PRICE", null=True),
        ),
    ]
