# Generated by Django 4.1.6 on 2023-02-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="type",
            field=models.CharField(db_column="PYMENT_TYPE", max_length=20, null=True),
        ),
    ]
