# Generated by Django 4.1.6 on 2023-02-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_payment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankPayment",
            fields=[
                (
                    "payment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payment.payment",
                    ),
                ),
            ],
            bases=("payment.payment",),
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "payment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payment.payment",
                    ),
                ),
            ],
            bases=("payment.payment",),
        ),
        migrations.AddField(
            model_name="payment",
            name="total",
            field=models.IntegerField(db_column="TOTAL", null=True),
        ),
        migrations.CreateModel(
            name="LoanPayment",
            fields=[
                (
                    "loan_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payment.loan",
                    ),
                ),
            ],
            bases=("payment.loan",),
        ),
    ]
