# Generated by Django 4.1.6 on 2023-02-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_bankpayment_loan_payment_total_loanpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="state",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("PAID", "Pagado"),
                    ("REFUSED", "Rechazado"),
                ],
                db_column="STATE",
                max_length=20,
            ),
        ),
    ]
